name: Continuous integration
on: [ push, pull_request ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
  build:
    name: Build
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bash ./gradlew build --stacktrace
  test:
    name: Test
    needs: [ setup, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: bash ./gradlew test --stacktrace
  assemble:
    name: Assemble
    needs: [ setup, build, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Assemble debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
